# Generated by Django 5.1.7 on 2025-04-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
